### ISSUE TITLE
Autenticate user in custom endpoint

### ISSUE THREAD

**Issue by emilpriverrc** [WP-API/authentication#11]
Hello, 

i have made a custom endpoint for a integration. Trying to find any information on how to verify consumer_secret and consumer_key.

do you people have any tips on what too look at? Any function/class to use?

Dear,
Emil

**Comment by TimothyBJacobs** [comment]
Hi emil,

This repo is for discussion of a future WordPress Core authentication mechanism, not for general support. I'd recommend checking out the [WordPress Stack Exchange](http://wordpress.stackexchange.com/) instance.
