### ISSUE TITLE
Required reading 

### ISSUE THREAD

**Issue by spacedmonkey** [WP-API/authentication#9]
Decided to put a list of required reading together. These are documents and other information that will be useful for developers interested in working on this project. 

- [The OAuth 2.0 Authorization Framework](https://tools.ietf.org/html/rfc6749)
- [OAuth 2.0 Dynamic Registration](https://tools.ietf.org/html/rfc7591)  
- [JSON Web Token (JWT) Profile   for OAuth 2.0 Client Authentication and Authorization Grants](https://tools.ietf.org/html/rfc7523)

Not directly related, but may also be useful 
- [OAuth 2.0 Token Introspection](https://tools.ietf.org/html/rfc7662)

**Comment by aaronpk** [comment]
Is this different than #2?
